### ISSUE TITLE
Pega service can't be configured as "LoadBalancer"

### ISSUE THREAD

**Issue by anujgarg06** [pegasystems/pega-helm-charts#279] opened 2021-04-29 19:24 UTC
**Describe the bug**

1. Pega ServiceType can't be configured as LoadBalancer. It always create "NodePort" as service type.
2. There is no way to configure "spec.loadBalancerSourceRanges" to limit access to few CIDR

**To Reproduce**
Configure pega values.yaml file for AWS and use ServiceType "LoadBalancer"

**Expected behavior**
Service Type in Kubernetes should use "LoadBalancer" but it is "NodePort"

**Chart version**
pega/pega 1.5.0

**Server (if applicable, please complete the following information):**
 - OS: Ubuntu 20.04
 - Environment: Amazon EKS 1.19
 - Database: Aurora PostgreSQL

**Additional context**
As per this template file: https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/templates/_pega-service.tpl 
spec:
  type:
  {{- if or (eq .root.Values.global.provider "gke") (eq .root.Values.global.provider "eks") -}}
  {{ indent 1 "NodePort" }}
  {{- else -}}
  {{ indent 1 (.node.service.serviceType | default "LoadBalancer") }}
  {{- end }}
   Specification of on which port the service is enabled
  ports:
  - name: http
    port: {{ .node.service.port }}
    targetPort: {{ .node.service.targetPort }}
  selector:
    app: {{ .name }}
**Error**: It seems, that it doesn't check ServiceType, because it is eks, it defaults it to "NodePort" I have changed manually to "LoadBalancer" which worked but it then reverted to NodePort as soon as i redeplyed helm chart. This is a critical error, forcing us to modify DNS again and again.

**Comment by sudeshjethoe** [comment] 2023-02-06 07:25
Similar issue here, we use kustomize to modify the helm chart after rendering to change the service type before deployment

**Comment by misterdorito** [comment] 2023-05-01 18:48
@anujgarg06 @sudeshjethoe is this still an issue?

**Comment by APegaDavis** [comment] 2023-06-05 18:37
@anujgarg06 @sudeshjethoe were you able to work around the issue?

**Comment by kishorv10** [comment] 2024-04-23 10:36
The issue is addressed in #610.

**Closed by kishorv10** 2024-04-23 10:36 UTC
