### ISSUE TITLE
Ability to set the HTTP thread pool size

### ISSUE THREAD

**Issue by lukaszkarnasiewicz** [pegasystems/pega-helm-charts#538] opened 2023-03-13 09:25 UTC
**Is your feature request related to a problem? Please describe.**
The default number of threads (200) is often inadequate and in certain usecases (i.e. CDH inbound) can cause extremely high concurrency when an instance is saturated, affecting performance, resilience and availability.

**Describe the solution you'd like**
Ability to set the maxThreads attribute via environmental variables

**Comment by kishorv10** [comment] 2024-04-22 10:32
The issue is addressed in #539 Hence closing it

**Closed by kishorv10** 2024-04-22 10:32 UTC
Labels: enhancement
