### ISSUE TITLE
Delivery of config files from helm charts causes confusion 

### ISSUE THREAD

**Issue by pega-embate** [pegasystems/pega-helm-charts#104] opened 2020-03-04 21:40 UTC
The pega helm charts currently deliver copies of prconfig.xml, prlog4j2.xml and context.xml.impl.  Upon deployment, these files overwrite the configuration provided by the pega image.  If the platform updated the prconfig.xml or prlog4j2.xml in a future version, the new versions would be wiped out after a helm deployment.    

I'd like to eliminate the delivery of the config files via helm by default and allow customers to add custom version of these files to config/deploy as needed (at there own risk).  If no custom config files are provided, the prconfig.xml and prlog4j2.xml will be deployed from the latest prweb.war and the context.xml.impl will be the version supplied in the pega-web-ready image (which is populated based on environment variables defined via helm).

**Comment by Emilio-Pega** [comment] 2020-03-05 12:16
@pega-embate This has come up before, according to the docs you should be able to set 
```
tier:
   - name: mytier
     prconfigPath: /path/to/file
```

However, I am under the impression that this does not work due to helm/helm#3276

Can you confirm that the documented override does not work?

Tried to get it confirmed in https://github.com/pegasystems/pega-helm-charts/issues/77 but the originator never confirmed one way or another before it was closed.

**Comment by pega-embate** [comment] 2020-03-05 14:53
@Emilio-Pega I do not see any reference to a prconfigPath sourced from values in the charts, so I agree this likely does not work as advertised today.  The charts do include the ability to specify a custom.prconfig in values but that would require specification of the full file text in values which would likely result in an escaping nightmare.    At the very least, the custom.prconfig should be a path to a local file.

**Comment by Emilio-Pega** [comment] 2020-03-05 15:21
Ya looks like the template hardcpodes the values https://github.com/pegasystems/pega-helm-charts/blob/754066f10ff423c218c1162265fb295f1eb0fed8/charts/pega/templates/_pega-config.tpl#L15  didn't always do that (if memory serves)

**Comment by pega-embate** [comment] 2020-03-05 15:34
I have confirmed that specifying a config path outside of the chart hierarchy does not work as @Emilio-Pega mentioned.  I can however add a new file to config/deploy and reference that directly in the template that pulls in the config (but if we wanted to go in this direction, this would need to be exposed from values)

I think the best solution would be to remove the current content of config/deploy (or change the names of the files and document that these files can be treated as a base of custom config) and allow customers to add custom config there.

**Comment by pega-embate** [comment] 2020-03-05 15:42
It looks like https://github.com/pegasystems/pega-helm-charts/pull/26 removed the ability to use values to specify a config file location.  @dcasavant Do you know if this change was intentional?

**Comment by dcasavant** [comment] 2020-07-11 00:06
Merged with #159

**Closed by dcasavant** 2020-07-11 00:06 UTC
Labels: enhancement
